apiVersion: v1
kind: Secret
metadata:
  name: saml-secret
type: Opaque
stringData:
  SSO_REALM: WildFly
  SSO_USERNAME: client-admin
  SSO_PASSWORD: client-admin
  SSO_SAML_CERTIFICATE_NAME: saml-app
  SSO_SAML_KEYSTORE: keystore.jks
  SSO_SAML_KEYSTORE_PASSWORD: password
  SSO_SAML_KEYSTORE_DIR: /etc/sso-saml-secret-volume
  SSO_SAML_LOGOUT_PAGE: /saml-app
  SSO_DISABLE_SSL_CERTIFICATE_VALIDATION: 'true'
  #SSO_HOSTNAME_HTTPS: https://saml-app-saml-test.apps.operator3-c11f.eapqe.psi.redhat.com/saml-app
  #SSO_URL: https://keycloak-saml-test.apps.operator3-c11f.eapqe.psi.redhat.com/auth
  