#!/bin/sh

jarFile=$(find /tmp/src -type f -iname "*-uberjar.jar")

if [ ! -f "$jarFile" ]; then
  echo "Error no wildfly uber jar found."
  exit 1
fi

java -Dopenshift -jar "$jarFile" 

chmod -R ug+rwX $JBOSS_HOME