#!/bin/bash

if [ -d "$JBOSS_HOME" ]; then
  if [ -f "$JBOSS_HOME/bin/openshift-launch.sh" ]; then
    exec "$JBOSS_HOME"/bin/openshift-launch.sh  
  else
    hostname=$(hostname -i)
    exec "$JBOSS_HOME"/bin/standalone.sh  -b $hostname -bmanagement 0.0.0.0
  fi
else
  echo "ERROR: No $JBOSS_HOME directory"
fi
